### ISSUE TITLE
csv files

### ISSUE THREAD

**Issue by parlange** [gemyxzhang/neural-subhalo-slope-data#1]
Hi @gemyxzhang 

I've been working with paltas and recently found your great work with subhalos.

Using make_images.py requires val_galaxies.csv and bad_galaxies.csv.

I want to reproduce your experiments. Could you provide an example for these csv files?

Thank you

**Comment by gemyxzhang** [comment]
These are provided by paltas and should be in your local install of the package. Please see https://github.com/swagnercarena/paltas/tree/main/paltas/Sources.
